DaveDuck321/GrapheneLang

codegen/builtin_types.py
codegen/interfaces.py
codegen/translation_unit.py
driver.py
target.py
targets/x86_64_linux.json

Not yet ready but I'd like your thoughts on this. The config file contains pretty much the bare minimum to generate the data layout string, so we might need to add more information in the future.
I went for a singleton cause I suspect many files in `codegen/` would need access to this information. If that's not the case then I'd rather refactor it as a class.

Add target config file and parser

---

codegen/__init__.py
codegen/builtin_types.py
codegen/interfaces.py
codegen/translation_unit.py
codegen/type_conversions.py
codegen/type_resolution.py
codegen/user_facing_errors.py
graphene_parser.py
parser/parser.c3
tests/generic_functions/sfinae_ambiguous.c3
tests/generic_types/duplicate_type_specialization.c3
tests/main_return_type/invalid.c3
tests/misc/ambiguous_function_call.c3
tests/misc/recursive_types.c3
tests/misc/recursive_types_unresolvable.c3
tests/misc/reference_nesting.c3
tests/regressions/builtin_redefinition.c3
tests/regressions/error_in_return_type.c3
tests/regressions/pattern_match_heap_array.c3
tests/regressions/std_redefinition.c3
tests/structs/init_list_with_wrong_name.c3
tests/structs/initializer_list_function_call_no_overloaded.c3
tests/structs/initializer_list_function_call_templated.c3
tests/void/arguments.c3
tests/void/heap_array.c3
tests/void/stack_array.c3
tests/void/structs.c3

I started writing this so that the LSP could dynamically load/ unload entire translation units worth of symbols but in the refactor it became convenient to make a number of related improvements/ simplifications.
- We no longer differentiate between specialized/ generic functions/ typedefs.
- We now handle function and type resolution in the same place with the same algorithms.
This has the advantage that: `decltype` is now possible, partial specializations just need to be turned on, and error messages are improved (we can finally display generic functions when overload resolution fails!!)
I have formalized function specialization in the following way:
```
Specializes and resolves the function corresponding to the correct definition
There are two types of function definition:
1) function …
```

Refactor type and function resolution

---

docs/types_overview.md
src/glang/codegen/builtin_callables.py
src/glang/codegen/expressions.py
src/glang/codegen/generatable.py
src/glang/codegen/interfaces.py
src/glang/codegen/type_conversions.py
src/glang/codegen/type_resolution.py
src/glang/codegen/user_facing_errors.py
src/glang/graphene_parser.py
tests/generic_functions/deduction_failure.c3
tests/generic_functions/generic_deduction_ignores_initializer_list.c3
tests/generic_functions/implicit_conversion_after_specialization.c3
tests/structs/init_list_implicit_struct.c3
tests/structs/init_list_to_adhoc_struct_parameter.c3
tests/structs/initializer_list_function_call_templated.c3
tests/structs/pattern_match_init_list.c3
tests/structs/pattern_match_init_list_fail.c3
tests/structs/struct_to_adhoc_struct_parameter.c3

Initializer lists have no `underlying_type` despite being a `TypedExpression`.  This made the whole interface kind of confusing to use. Now `TypedExpression` no longer requires an underlying type, instead, it has a `result_type` (which is the type an expression would collapse to if no implicit conversion was executed).
This fixes #124 and a few other confusing template/ initializer list interactions.
These fixes allow us to *finally* match the type behavior described in the docs (namely initializer lists creating new "compatible" structs).
These fixes also exposed the awkward behavior where implicit conversion is disabled when using specialized templates so I had to fix this for the parser to compile.
```
function [T] fn : (a : T, b : T) -> ...
fn<isize>(8, 8); // 8 is now implicitly …
```

Allow automatic initializer list type deduction

---

.vscode/launch.json
pyproject.toml
src/glang/codegen/builtin_types.py
src/glang/codegen/expressions.py
src/glang/codegen/generatable.py
src/glang/codegen/interfaces.py
src/glang/codegen/translation_unit.py
src/glang/codegen/type_conversions.py
src/glang/codegen/type_resolution.py
src/glang/graphene_parser.py
tests/constants/ufcs.c3
tests/misc/arguments_are_mutable.c3

- Function arguments that were passed by value should be mutable
- Handle arguments passed to `hatch run test:run`
- Allow UFCS calls to match with both `mut&` and `&` (`mut&` preferred)
- Fix debug configuration

Small QoL improvements

---

src/glang/lib/std/rb_tree.c3
src/glang/lib/std/wrappers.c3
tests/stdlib/rb_tree/basic.c3
tests/stdlib/rb_tree/extended.c3
tests/stdlib/rb_tree/minmax.c3

Required for an efficient `map` container.
Insertion and search work, but we are missing ~~deletion and~~ the traversals.

Add red-black trees to the standard library

---

.github/workflows/graphene_tests.yml
src/glang/codegen/__init__.py
src/glang/codegen/builtin_callables.py
src/glang/codegen/builtin_types.py
src/glang/codegen/debug.py
src/glang/codegen/expressions.py
src/glang/codegen/generatable.py
src/glang/codegen/interfaces.py
src/glang/codegen/translation_unit.py
src/glang/codegen/type_conversions.py
src/glang/codegen/type_resolution.py
src/glang/graphene_parser.py
tests/arrays/alignment_aarch64_linux.c3
tests/arrays/alignment_x86_64_linux.c3
tests/arrays/md_heap_array.c3
tests/debug/basic.c3
tests/debug/variables.c3
tests/misc/string_constants.c3
tests/run_tests.py

I think you can take a look now - it's pretty functional.
The compiler now always emits LLVM-style debugging information (basically DWARF).
- The format is pretty straightforward, but it might help to look at some example IR before you review
- To get line number support, we need to pass the `Meta` from the parser to every single expression we codegen
- That's quite tedious unfortunately, but there's no other way
- The `generate_ir()` function now needs more inputs and has a second output, to handle the metadata
- To get type and variable support (`gdb` needs to know how to read variables off of memory), we need to serialize each type
- That's quite tricky and I don't really have a nice solution yet - maybe we should do it during type resolution to avoid cycles, etc but also this is …

Emit basic debugging information

---

src/glang/codegen/builtin_types.py
src/glang/codegen/mangling.py
tests/debug/basic.c3
tests/generic_types/basic_usage.c3

Based on https://itanium-cxx-abi.github.io/cxx-abi/abi.html#mangling, which is what GCC and Clang use. 
Everything works (by inspection), but I'll add tests before merging.
I haven't implemented compression yet (and not sure it's worth it), but it's necessary if we want to be 100% compatible with other toolchains.

Implement Itanium C++ ABI name mangling

---

tests/run_tests.py

This has been bothering me for ages: having to pass a path to the --test
argument that is relative to the tests/ directory means you can't use your
shell's autocomplete.

run_tests.py improvements

---

src/glang/codegen/generatable.py
src/glang/graphene_parser.py
src/glang/lib/std/format.c3
src/glang/lib/std/json.c3
src/glang/lib/std/wrappers.c3
tests/regressions/return_void.c3
tests/stdlib/print.c3

Also fixed type-checking when returning `void` from a function (we weren't doing any...)

Change return type of `write()` to void

---

bootstrap.sh
pyproject.toml

- Relax dependency requirements to allow newer minor versions; required when packaging for a distro
- Use absolute paths in `bootstrap.sh` instead of relative paths, as we set the working directory with `env -C`
If we don't need anything else for the quick bootstrap PR, then we can make 0.4.0 release.

Fix RPM build

---

.github/workflows/lint.yml

Hatch doesn't pass `--exit-non-zero-on-fix` to ruff, so it always returns 0 and the CI always passes. This is a quick workaround.

lint.yml: make ruff errors fail the CI

---

.github/workflows/graphene_tests.yml
src/glang/driver.py

This PR moves most of what clang was doing into graphene. Our new pipeline is:
1) Compile the graphene sources into LLVM
2) Optimize the LLVM
3) Compile the LLVM into an object
4) Compile our runtime.S into an object
5) Link with `ld.lld`
I suspect I'm missing some target-specific stuff in the `opt` step since clang is able turn on/off specific passes but I'm assuming this doesn't really make a difference.
Overall, this PR adds code but slightly reduces the number of conditional branches + adds support for compiling multiple sources into a static library (if for some reason you can find a graphene program that won't violate the ODR).
This is the first step in graphene translation units and allows us to support targets without a clang frontend but with a llvm backend (I can think of one …

Move clang driver functionality into Graphene

---

.github/workflows/graphene_tests.yml
tests/run_tests.py

Fix the following error in tests that do _not_ run with `--use-crt`:
```
lli: Native platforms require a process symbols JITDylib
```
by disabling JIT platform support.
Not 100% sure on what we lose, but I think the "native" platform just calls `dlopen()` and `dlclose()` on each SO.
See https://reviews.llvm.org/D144276 and https://reviews.llvm.org/D99416.

LLVM 18 support

---

.github/workflows/graphene_tests.yml
.github/workflows/lint.yml

Hatch updates keep breaking our CI checks...
v1.10 lets us pin stuff like the `ruff` version used, so perhaps that's gonna be more stable going forward, but right now it just updates and breaks the linting/formatting checks

Use hatch v1.9.4 on CI

---

src/glang/codegen/builtin_types.py
src/glang/lib/std/arithmetic.c3
src/glang/lib/std/json.c3
src/glang/lib/std/logical.c3
src/glang/lib/std/map.c3
src/glang/lib/std/rb_tree.c3
src/glang/lib/std/span.c3
src/glang/lib/std/string.c3
src/glang/lib/std/vector.c3
src/glang/target.py
tests/json/array_comma_after_close.c3
tests/json/array_extra_comma.c3
tests/json/echo.c3
tests/json/object_empty_key.c3
tests/json/string_allowed_escapes.c3
tests/json/string_incomplete_escape.c3
tests/json/string_unescaped_tab.c3
tests/regressions/di_struct_offset.c3
tests/stdlib/map.c3
tests/stdlib/rb_tree/basic.c3
tests/stdlib/rb_tree/extended.c3
tests/stdlib/rb_tree/minmax.c3
tests/stdlib/rb_tree/traversal.c3

The goal was to use `Map` in the JSON library, but there's a bunch of stuff in this PR:
- Add `Map`, based on `RB_Tree`
- Fixed the debug information generated for struct members
- Add RB tree `predecessor()` and `successor()` functions
- Add RB tree and Map iterators
- Change some comparisons to take their arguments by references (the only straightforward way to compare two `JSON_Node`s is by looking at their address... but to pass them by reference means that we have to pass everything else by reference too, even `int`s)

Add Map container and RB tree iterator

---

pyproject.toml

Lark 1.2.2 was release on August 13. This was marked as backwards compatible with lark 1.1 (hence pulled in by Hatch). Turns out it is not in fact backwards compatible and was breaking our bootstrap on a fresh checkout.
This PR reverts lark to the latest backwards compatible version.

Fix bootstrap broken by lark 1.2.2

---

tests/run_tests.py
tests/test_config_grammar.lark
tests/test_config_parser.py

I've been working on function pointers, callables, and an over-loadable [] operator... Unfortunately this is becoming unwieldy and I'll have to regress the multidimensional array test to avoid touching the pattern matching logic in the same diff.
This PR adds the testing infrastructure to make this possible without completely deleting the test.

Testing: add `@FAILING` tag

---

.github/workflows/lint.yml

The `ubuntu-latest` image update to a version that prevent `pip --user` (and tells us to use `apt`). We can work around this by creating virtual environments.

Fix the CI lint stage

---

.github/workflows/graphene_tests.yml
.github/workflows/lint.yml
pyproject.toml
src/glang/codegen/debug.py
src/glang/codegen/type_resolution.py
tests/run_tests.py
tests/test_config_parser.py

The test runner now accepts a list of paths, and like `pytest`, these can be either a test file or directory to search for tests. If no paths are provided, then it searches the `tests/` directory instead (the existing behaviour).
I've also (finally) fixed that bug where the test config parser would crash if the file was not a test.
This and some project changes let us use `hatch test [args...]` to launch the test runner, instead of `hatch run dev:test [args...]` that we have to do today.

Improve the test runner and switch to `hatch test`

---

bootstrap.sh

I'm looking through https://github.com/DaveDuck321/GrapheneLang/pull/170. Thought this would be reasonable as a prerequisite.
This PR introduces bootstrap stage 6 as a dedicated tag (which was previously pulled directly from master).
The reasoning:
1) We can add index operators to the standard library
2) https://github.com/DaveDuck321/GrapheneLang/pull/170 won't need to mess around with `runtime.S` (which was broken due to the syscalls conflict).

Give `bootstrap/6` a dedicated tag

---

src/glang/driver.py

I updated LLVM and it broke my tests by inserting a `strlen` :crying_cat_face:
This seems more future-proof than listing them all.

Disable production of all libcalls
